### PR TITLE
Enable CodeQL

### PR DESCRIPTION
**Pull request by adityamandaleeka**
Attempting to enable CodeQL in our CI pipeline.

@twsouthwick @dougbu @Tratcher

### CODE REVIEW

**Comment by twsouthwick** [comment]
How do we verify that it works? I don't see anything in the builds about CodeQL - usually I've seen it as a separate check here

**Comment by adityamandaleeka** [comment]
I set it to only run on internal builds, so I wouldn't expect to see anything new here.

**Comment by adityamandaleeka** [comment]
@Tratcher I followed a general set of instructions that was sent to a bunch of teams (and therefore isn't at all tailored for our infrastructure/Arcade)... what @dougbu did in YARP is probably closer to what we should be doing here.

**Comment by dougbu** [comment]
I also wanted to be as consistent as possible across the branches. Tasks are auto injected (when you let them be) _only_ in the repository's default branch.

**Review by Tratcher — APPROVED** [review]

**Pull request merged**
