### PR TITLE
Add HtmlTextWriter and required support

### LINKED ISSUE #378: Ask About HtmlTextWriter
## Summary

Our repo uses `HtmlTextWriter` which is not supported by ASP.NetCore and this adapters.
I want to ask if there is equivalent and if there is plan to add them to adapter.

## Motivation and goals

We need migrate code (an API in Sharepoint) to ASP.NetCore and we find that the APIs are not supported by ASP.NetCore.

## In scope

`HtmlTextWriter`

I only found a 3rd-party package [HtmlTextWriter](https://www.nuget.org/packages/HtmlTextWriter)
Is there a plan to add HtmlTextWriter into adapters?

## Examples
Use HtmlTextWriter to encode url
```C#
HtmlTextWriter writer = new HtmlTextWriter(new StringWriter(new StringBuilder(), CultureInfo.InvariantCulture));
writer.Write(url)
```

### PR DESCRIPTION
**Pull request by twsouthwick**
This is a port of HtmlTextWriter with the following changes:

- `HtmlTextWriter.[Enter|Exit]Style(...)` methods (4 total) are not supported. The `Style` class brings in a lot of additional stuff we probably don't want to support
- HashTable usage has been switched to Dictionary<,>
- Manual array management has been switched to lists
- Helper structs have been made into readonly records to simplify definition and usage
- Annotated for nullability

TODO:

- [ ] Add some tests

Fixes #378

### CODE REVIEW

**Comment by Clounea** [comment]
Inspired by the tests in this repo https://github.com/mfeingol/htmltextwriter, I think you could add the test like below. The render code is from https://learn.microsoft.com/en-us/dotnet/api/system.web.ui.htmltextwriter.addattribute?view=netframework-4.8.1, and the expected string is result I get from .NetFramework project with same render code.
```
[Fact]
public void RenderCustomControl()
{
    using MemoryStream mem = new MemoryStream();
    using StreamWriter sw = new StreamWriter(mem);
    using HtmlTextWriter writer = new HtmlTextWriter(sw);

    // Set attributes and values along with attributes and styles  
    // attribute defined for a <span> element.
    writer.AddAttribute(HtmlTextWriterAttribute.Onclick, "alert('Hello');");
    writer.AddAttribute("CustomAttribute", "CustomAttributeValue");
    writer.AddStyleAttribute(HtmlTextWriterStyle.Color, "Red");
    writer.AddStyleAttribute("Customstyle", "CustomStyleValue");
    writer.RenderBeginTag(HtmlTextWriterTag.Span);
    // Create a space and indent the markup inside the 
    // <span> element.
    writer.WriteLine();
    writer.Indent++;
    writer.Write("Hello");
    writer.WriteLine();

    // Controls the encoding of markup attributes
    // for an <img> element. Simple known values 
    // do not need encoding.
    writer.AddAttribute(HtmlTextWriterAttribute.Alt,
        "Encoding, \"Required\"",
        true);
    writer.AddAttribute("myattribute",
        "No &quot;encoding &quot; required",
        false);
    writer.RenderBeginTag(HtmlTextWriterTag.Img);
    writer.RenderEndTag();
    writer.WriteLine();

    // Create a non-standard markup element.
    writer.RenderBeginTag("MyTag");
    writer.Write("Contents of MyTag");
    writer.RenderEndTag();
    writer.WriteLine();

    // Create a manually rendered <img> element
    // that contains an alt attribute.
    writer.WriteBeginTag("img");
    writer.WriteAttribute("alt", "A custom image.");
    writer.Write(HtmlTextWriter.TagRightChar);
    writer.WriteEndTag("img");
    writer.WriteLine();

    writer.Indent--;
    writer.RenderEndTag();

    writer.Flush();
    mem.Position = 0;
    string html = Encoding.UTF8.GetString(mem.GetBuffer());

    const string expected = "<span onclick=\"alert(&#39;Hello&#39;);\" CustomAttribute=\"CustomAttributeValue\" style=\"color:Red;Customstyle:CustomStyleValue;\">\r\n\tHello\r\n\t<img alt=\"Encoding, &quot;Required&quot;\" myattribute=\"No &quot;encoding &quot; required\" />\r\n\t<MyTag>\r\n\t\tContents of MyTag\r\n\t</MyTag>\r\n\t<img alt=\"A custom image.\"></img>\r\n</span>";
    Assert.Equal(expected, html);
}
```

**Comment by twsouthwick** [comment]
@Clounea you interested in adding that test? The `expected` variable could use a raw string, but other than that, it's probably a good start

**Comment by Clounea** [comment]
> @Clounea you interested in adding that test? The `expected` variable could use a raw string, but other than that, it's probably a good start

Yes, but how? I tried pushing changes to this branch but I don't have access. Do you know how to add the test?

**Comment by twsouthwick** [comment]
Oh! I'll go ahead and add it - must be a permissions issue

**Comment by douglaseccker** [comment]
@twsouthwick Is there any plan to merge this PR?

**Comment by CZEMacLeod** [comment]
Out of interest, why was this discarded?

**Pull request closed without merging**
