### PR TITLE
Consolidate session APIs into main library

### PR DESCRIPTION
**Pull request by twsouthwick**
This moves the session infrastructure into the main library. The current SessionState library existed because there was a dependency on System.Text.Json so we didn't want to force people to use that. However, now that can be opted into for a specific implementation of ISessionKeySerializer. This has been kept in the separate project which has been renamed to Microsoft.AspNetCore.SystemWebAdapters.SystemTextJson

### CODE REVIEW

**Review by mjrousos — APPROVED** [review]
LGTM

**Comment by twsouthwick** [comment]
@tratcher any concerns with this change in layering?

**Comment by Tratcher** [comment]
I've added the Breaking-Change label to remind us to call out the package name change in the release notes.

**Comment by Tratcher** [comment]
SystemWebAdapters.SystemTextJson is an odd name since it doesn't say anything about session, serializers, etc.

**Comment by twsouthwick** [comment]
Yeah, the idea I had was this would be for any JSON serialization needs we may need, not necessarily tied to session/auth/something specific.

**Comment by Tratcher** [comment]
No concerns other than the naming. Cross check it with @danroth27 and @adityamandaleeka.

**Comment by twsouthwick** [comment]
Closing in favor of https://github.com/dotnet/systemweb-adapters/issues/131

**Pull request closed without merging**
